[package]
name = "server"
version = "0.1.0"
authors = ["Moritz Riede <mriede@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.2.1"
serde   = "1.0.105"
tokio   = "0.2.14"
ws      = "0.9.1"
